package com.Spring.model;
// Generated Aug 21, 2016 2:31:51 PM by Hibernate Tools 3.6.0



/**
 * Studentcanteen generated by hbm2java
 */
public class Studentcanteen  implements java.io.Serializable {


     private Integer studentCanteenId;
     private Student student;
     private Integer charge;

    public Studentcanteen() {
    }

    public Studentcanteen(Student student, Integer charge) {
       this.student = student;
       this.charge = charge;
    }
   
    public Integer getStudentCanteenId() {
        return this.studentCanteenId;
    }
    
    public void setStudentCanteenId(Integer studentCanteenId) {
        this.studentCanteenId = studentCanteenId;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Integer getCharge() {
        return this.charge;
    }
    
    public void setCharge(Integer charge) {
        this.charge = charge;
    }




}


