package com.Spring.model;
// Generated Aug 21, 2016 2:31:51 PM by Hibernate Tools 3.6.0



/**
 * Studenthostal generated by hbm2java
 */
public class Studenthostal  implements java.io.Serializable {


     private Integer studentHostalId;
     private Student student;
     private Integer rant;

    public Studenthostal() {
    }

    public Studenthostal(Student student, Integer rant) {
       this.student = student;
       this.rant = rant;
    }
   
    public Integer getStudentHostalId() {
        return this.studentHostalId;
    }
    
    public void setStudentHostalId(Integer studentHostalId) {
        this.studentHostalId = studentHostalId;
    }
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }
    public Integer getRant() {
        return this.rant;
    }
    
    public void setRant(Integer rant) {
        this.rant = rant;
    }




}


